name: hardhat-waffle CI

on: [push]
concurrency: ci

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

  name: CangeME1
  strategy:
    matrix:
      node: [16]
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: yarn
    - name: Install
      run: yarn --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Run tests
      run: yarn test
